### ISSUE TITLE
Inconsistencies in equations

### ISSUE THREAD

**Issue by VladimirIvan** [blandry/Bilevel.jl#1]
Hi,
I've been going through the equations in the [paper](http://arxiv.org/abs/1906.04292) and found the following inconsistencies:

- The mass matrix is computed from `q_i` instead of `q_{i+1}` [here](https://github.com/blandry/Bilevel.jl/blob/43519162f54f3d0322ac6e4d928b760508e6776a/src/trajopt_semidirect.jl#L197).
- Similarly the torques `tau_i` (`u0`) are used in the code [here](https://github.com/blandry/Bilevel.jl/blob/43519162f54f3d0322ac6e4d928b760508e6776a/src/trajopt_semidirect.jl#L211) instead of `tau_{i+1}` used in the paper. Is this a convention to store `m-1` and `u0` does indeed refer to `tau_{i+1}`?
- `Qd` and `rd` in the [code](https://github.com/blandry/Bilevel.jl/blob/43519162f54f3d0322ac6e4d928b760508e6776a/src/contact_sim.jl#L298) don't match the paper. It seems the contact Jacobian is defined differently. Is that correct?

Additionally, the torque vector `tau` is size `n+6` for floating based systems as defined [here](https://github.com/blandry/Bilevel.jl/blob/43519162f54f3d0322ac6e4d928b760508e6776a/src/trajopt_semidirect.jl#L9). Wouldn't this allow the planner to apply forces/torques directly on the floating base? 
Most dynamics equations define `tau` as size `n` and pre-multiply it with a selection matrix to get a vector of size n+6. The paper uses the equation for a manipulator so the derivation in the paper is correct.

**Comment by blandry** [comment]
Hi,

Thanks for the very close read-through. I hope I can answer your questions to your satisfaction.

> The mass matrix is computed from q_i instead of q_{i+1} here.

You are correct about this and you could consider it a mistake. I'll add a few details though. In the context of trajectory optimization, I have tried both (`H(q_i)` and `H(q_{i+1})`) and didn't see a big difference in practice (unlike for, say, the jacobians). There is also a reason (although not very good one) for this mistake. During development, I also tested this algorithm for simulation only. In the context of simulation, `q_0` is known and therefore not having to autodiff through `H` seemed like a trade-off worth considering. Perhaps the right way to do this trade-off can be found in the original hard contact [paper](https://digital.library.unt.edu/ark:/67531/metadc708291/m2/1/high_res_d/751199.pdf). In section 3.1, the authors explain how `H` (`M` in their paper) is actually evaluated at `H(q_i + v_i*t)` to keep the objective linear. But again, in the context of trajectory optimization I think you are correct and there is no good reason to do this really (since both `q_i` and `q_{i+1}` are decision variables).

> Similarly the torques tau_i (u0) are used in the code here instead of tau_{i+1} used in the paper. Is this a convention to store m-1 and u0 does indeed refer to tau_{i+1}?

This is also correct (as in both the code and you are correct). If you look [here](https://github.com/blandry/Bilevel.jl/blob/43519162f54f3d0322ac6e4d928b760508e6776a/src/trajopt_semidirect.jl#L9) you can see that the control array is one element shorter than the state array, so `u0` is indeed `tau_{i+1}`.

> Qd and rd in the code don't match the paper. It seems the contact Jacobian is defined differently. Is that correct?

Yup this is also correct. The Jacobian is defined slightly differently in the code and in the paper, in the sense that the Jacobian in the code "includes" the `F` from the paper i.e. `J_code = J_paper * F_paper`. This can be seen [here](https://github.com/blandry/Bilevel.jl/blob/43519162f54f3d0322ac6e4d928b760508e6776a/src/contact.jl#L79). Note that in the [code](https://github.com/blandry/Bilevel.jl/blob/43519162f54f3d0322ac6e4d928b760508e6776a/src/contact.jl#L42), the `F` also contains the weight of the rigid body, so that it keeps the forces in a good numerical range.

> Wouldn't this allow the planner to apply forces/torques directly on the floating base?

Absolutely! And I handled this (inelegantly) by forcing those control inputs to be between zero and zero when setting the control limits (when setting up the traj opt problems themselves). For example, little dog used `u_min = vcat(zeros(3), -u_mag_max * ones(12))` and `u_max = vcat(zeros(3), u_mag_max * ones(12))` (not 6 floating dof but 3, because little dog was constrained to be in the plane so only has `x`, `y` and `theta`.

I hope this helps!

**Comment by VladimirIvan** [comment]
Thank you for the explanation. These are very clever modifications. 
I also want to say that I really enjoyed reading the paper, I cannot stress enough how much I appreciate the how clearly it's written, and that the code is available. It looks like the paper is in the review/publication process. Good luck!
